author: Jeff Bergier, Landon Epps
description: Two iOS developers talk about working in Japan, finding a job, and recent Apple news.
long_description: >
  Jeff is a senior iOS developer in Tokyo and Landon is an iOS developer looking for his first job.
  They talk about a range of topics including finding a software engineering job, working in Japan,
  living abroad, coding bootcamps, WWDC, new features in Swift and SwiftUI, and recent Apple news.
email: webmaster@nstokyoview.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-142468577-1
hashtag: NSTokyoView
itunes_podcast_id: 1478532626
itunes_podcast_url: https://podcasts.apple.com/us/podcast/nstokyoview/id1478532626
language: en
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: NSTokyoView
url: https://nstokyoview.com/
