author: alice
description: Example podcast description.
description_long: Example Podcast Title is a podcast about podcasting.
email: podcast@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: examplehashtag
itunes_podcast_url: https://itunes.apple.com/us/podcast/examplepodcasttitle/id9999999999
keywords: comma,separated,keywords
language: en
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Example Podcast Title
url: http://landonepps.github.io/podcast/
