author: Jeff Bergier, Landon Epps
description: Example podcast description.
description_long: Example Podcast Title is a podcast about podcasting.
email: podcast@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-142468577-1
hashtag: NSTokyoView
itunes_podcast_url: https://itunes.apple.com/us/podcast/examplepodcasttitle/id9999999999
language: en
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: NSTokyoView
url: https://nstokyoview.com/
